cardjson =  {
    "Dominion": [
        "Fosa",
        "Kaplica",
        "Piwnica",
        "Warsztat",
        "Wioska",
        "Ku\u017ania",
        "Lichwiarz",
        "Milicja",
        "Ogrody",
        "Przebudowa",
        "Sala tronowa",
        "Urz\u0119dnik",
        "Biblioteka",
        "Festyn",
        "Kopalnia",
        "Laboratorium",
        "Sala obrad",
        "Targowisko",
        "Wied\u017ama",
        "Kupiec",
        "Wasal",
        "Zwiastun",
        "K\u0142usownik",
        "Bandyta",
        "Wartownik",
        "R\u0119kodzielnik"
    ],
    "Intryga": [
        "Dziedziniec",
        "Giermek",
        "Tajna komnata",
        "Kanciarz",
        "Maskarada",
        "Rudera",
        "Studnia \u017cycze\u0144",
        "Westybul",
        "Zarz\u0105dca",
        "Baron",
        "Huta \u017celaza",
        "Mennica",
        "Most",
        "Osada g\u00f3rnicza",
        "Spiskowiec",
        "Zwiadowca",
        "Danina",
        "Faktoria",
        "Oprawca",
        "Rozbudowa",
        "Sabota\u017cysta",
        "Starosta",
        "S\u0142ugus",
        "Harem",
        "Szlachta"
    ],
    "Przysta\u0144": [
        "Latarnia morska",
        "Przysta\u0144",
        "Wioska tubylc\u00f3w",
        "Bocianie gniazdo",
        "Magazyn",
        "Przemytnicy",
        "Wioska rybacka",
        "Karawana",
        "Kieszonkowiec",
        "Mapa skarbu",
        "Wyspa",
        "Wy\u0142awiacz",
        "Bazar",
        "Nabrze\u017ce",
        "Okr\u0119t kupiecki",
        "Przycz\u00f3\u0142ek",
        "Skarbiec",
        "Strateg",
        "Embargo",
        "Po\u0142awiacz pere\u0142",
        "Ambasador",
        "Morska wied\u017ama",
        "Nawigator",
        "Okr\u0119t piracki",
        "Okr\u0119t widmo",
        "Zdobywca"
    ],
    "Przysta\u0144 v2": [
        "Morska czarownica",
        "Mapa morska",
        "Astrolabium",
        "Ma\u0142pa",
        "Baseny p\u0142ywowe",
        "Blokada",
        "\u017beglarz",
        "Korsarz",
        "Pirat"
    ],
    "Z\u0142oty wiek": [
        "Stra\u017cnica",
        "Biskup",
        "Kamienio\u0142om",
        "Monument",
        "Wioska robotnicza",
        "Miasto",
        "Mincerz",
        "Mot\u0142och",
        "Sk\u0142adnica",
        "Krocie",
        "Wielki targ",
        "Bank",
        "Modernizacja",
        "P\u0142atnerz",
        "Rada kr\u00f3lewska",
        "Domokr\u0105\u017cca",
        "Kredyt",
        "Szlak handlowy",
        "Talizman",
        "Kontrabanda",
        "Kr\u00f3lewska piecz\u0119\u0107",
        "Rachuba",
        "Szarlatan",
        "Z\u0142oty interes",
        "Naci\u0105gacze"
    ],
    "Z\u0142oty wiek v2": [
        "Anvil",
        "Clerk",
        "Investment",
        "Tiara",
        "Charlatan",
        "Collection",
        "Crystal Ball",
        "Magnate",
        "War Chest"
    ],
    "W g\u0142\u0105b l\u0105du/Hinterlands": [
        "Rozdro\u017ce",
        "Z\u0142oto g\u0142upc\u00f3w",
        "Oaza",
        "Pies str\u00f3\u017cuj\u0105cy",
        "Rozw\u00f3j",
        "Tunel",
        "Zmowa",
        "Handlarz",
        "Nomadzi",
        "Szlak",
        "Tkaczka",
        "Zamorski kupiec",
        "Z\u0142ota r\u0105czka",
        "Berserk",
        "Chatka wied\u017amy",
        "Gospoda",
        "Go\u015bciniec",
        "Kartograf",
        "Kocio\u0142ek",
        "Ko\u0142odziej",
        "Murgrabia",
        "Przekupie\u0144",
        "Stadnina",
        "Suk",
        "Pogranicze",
        "Pola uprawne"
    ],
    "W nieznane!/Adventures": [
        "Ch\u0142op",
        "Moneta obiegowa",
        "Pa\u017a",
        "Szczuro\u0142ap",
        "Wyburzenie",
        "Amulet",
        "Loch",
        "Narz\u0119dzia",
        "Przewodnik",
        "Stra\u017cnik karawany",
        "Duplikat",
        "\u0141owczy",
        "Port",
        "Pos\u0142aniec",
        "Przemiana",
        "Sk\u0105piec",
        "Sroka",
        "Bagienna wied\u017ama",
        "Bajarz",
        "Karoca",
        "Mostowy troll",
        "Nawiedzony las",
        "Odleg\u0142y l\u0105d",
        "Olbrzym",
        "Relikt",
        "Rzemie\u015blnik",
        "Sprzedawca wina",
        "Zaginione miasto",
        "Zaginiony skarb",
        "Najemnik"
    ],
    "Imperium": [
        "In\u017cynier",
        "Dzielnica",
        "Kr\u00f3lewski kowal",
        "W\u0142adca",
        "Obozowisko/Zdobycz",
        "Osadnicy/Gwarna wioska",
        "Patrycjusz/Emporium",
        "Czarodziejka",
        "Gladiator/Fortuna",
        "Katapulta/G\u0142azy",
        "Targ rolny",
        "Wy\u015bcig rydwan\u00f3w",
        "Zamki",
        "Ofiara",
        "\u015awi\u0105tynia",
        "Willa",
        "Archiwum",
        "Dziki gon",
        "Forum",
        "Kapita\u0142",
        "Klejnot",
        "Korona",
        "Legionista",
        "Ogrodnik"
    ],
    "Pie\u015b\u0144 nocy/Nocturne": [
        "Druid",
        "Klasztor",
        "Obro\u0144ca",
        "Tropiciel",
        "Wierny pies",
        "Wr\u00f3\u017cka",
        "G\u0142upiec",
        "Leprechaun",
        "Miasto duch\u00f3w",
        "Nocny str\u00f3\u017c",
        "Odmieniec",
        "Sekretna jaskinia",
        "Bard",
        "B\u0142ogos\u0142awiona wioska",
        "Cmentarz",
        "Diabelski warsztat",
        "Egzorcysta",
        "Nekromanta",
        "Pasterz",
        "Tajne zebranie",
        "Zasadzka",
        "Bo\u017cek",
        "Gn\u0119biciel",
        "Grzeszny przybytek",
        "Krypta",
        "Przekl\u0119ta wioska",
        "Puk",
        "Szewc",
        "\u015awi\u0119ty gaj",
        "Tragiczny bohater",
        "Wampir",
        "Wilko\u0142ak",
        "Naje\u017ad\u017aca"
    ],
    "Renesans": [
        "Border Guard",
        "Ducat",
        "Lackeys",
        "Acting Troupe",
        "Cargo Ship",
        "Experiment",
        "Improve",
        "Flag Bearer",
        "Hideout",
        "Inventor",
        "Mountain Village",
        "Patron",
        "Priest",
        "Research",
        "Silk Merchant",
        "Old Witch",
        "Recruiter",
        "Scepter",
        "Scholar",
        "Sculptor",
        "Seer",
        "Spices",
        "Swashbuckler",
        "Treasurer",
        "Villain"
    ],
    "Menagerie": [
        "Black Cat",
        "Sleigh",
        "Supplies",
        "Camel Train",
        "Goatherd",
        "Scrap",
        "Sheepdog",
        "Snowy Village",
        "Stockpile",
        "Bounty Hunter",
        "Cardinal",
        "Cavalry",
        "Groom",
        "Hostelry",
        "Village Green",
        "Barge",
        "Coven",
        "Displace",
        "Falconer",
        "Gatekeeper",
        "Hunting Lodge",
        "Kiln",
        "Livery",
        "Mastermind",
        "Paddock",
        "Sanctuary",
        "Fisherman",
        "Destrier",
        "Wayfarer",
        "Animal Fair"
    ],
    "Zdobycze": [
        "Grota",
        "Klatka",
        "Poszukiwania",
        "Szamanka",
        "Zdobione jajo",
        "Nadzorca",
        "Pasa\u017cer na gap\u0119",
        "Syrena",
        "Ustronna kapliczka",
        "Bagienne chaty",
        "Gondola",
        "\u0141owca skarb\u00f3w",
        "Majtek",
        "Okr\u0119t flagowy",
        "Rozbitek",
        "Rysownik map",
        "St\u00f3\u0142 warsztatowy",
        "Sznur",
        "Tygiel",
        "Urodzaj",
        "Wioska portowa",
        "Zej\u015bcie na l\u0105d",
        "Bogata wioska",
        "Drakkar",
        "Figurka",
        "Fregata",
        "Kilof",
        "Kopalnia srebra",
        "Kwatermistrz",
        "Oszust",
        "Pielgrzym",
        "Powi\u0119kszenie",
        "Rzezimieszek",
        "Starszy oficer",
        "Szlak g\u00f3rniczy",
        "Wisior",
        "Zakopany skarb",
        "Za\u0142oga",
        "Worek \u0142up\u00f3w",
        "Kr\u00f3lewska kasa"
    ],
    "Promo": [
        "Czarny rynek",
        "Ksi\u0105\u017c\u0119",
        "Zask\u00f3rniak",
        "Kapitan",
        "Sauna/Przer\u0119bel"
    ],
    "Zdarzenie": [
        "Ja\u0142mu\u017cna",
        "Po\u017cyczka",
        "Wyprawa",
        "Na czarn\u0105 godzin\u0119",
        "Festyn obwo\u017any",
        "Zwiady",
        "Ekspedycja",
        "Ognisko",
        "Plan",
        "Prom",
        "Misja",
        "Pielgrzymka",
        "Bal",
        "Cie\u015bnina",
        "Najazd",
        "Wymiana",
        "Szkolenie",
        "Zapomniane rzemios\u0142o",
        "Dziedzictwo",
        "Przecieranie szlaku",
        "Triumf",
        "Aneksja",
        "Datek",
        "Awans",
        "Podatek",
        "Zej\u015bcie",
        "Bankiet",
        "Rytua\u0142",
        "Solna kl\u0105twa",
        "Za\u015blubiny",
        "Gratka",
        "Podb\u00f3j",
        "Dominacja",
        "Delay",
        "Desperation",
        "Gamble",
        "Pursue",
        "Ride",
        "Toil",
        "Enhance",
        "March",
        "Transport",
        "Banish",
        "Bargain",
        "Invest",
        "Seize the Day",
        "Commerce",
        "Demand",
        "Stampede",
        "Reap",
        "Enclave",
        "Alliance",
        "Populate",
        "Zakopywanie",
        "Dor\u0119czenie",
        "Po\u015bpiech",
        "Unik",
        "Zagro\u017cenie",
        "Lustrzana kopia",
        "Napa\u015b\u0107",
        "Przygotowania",
        "Szabrowanie",
        "Wyj\u015bcie w morze",
        "W\u0119dr\u00f3wka",
        "Wir",
        "Pl\u0105drowanie",
        "Inwazja",
        "Rozkwit"
    ],
    "Krajobraz": [
        "Akwedukt",
        "Arena",
        "Bazylika",
        "Fontanna",
        "Fort rozb\u00f3jnik\u00f3w",
        "Grobowiec",
        "Kolumnada",
        "Labirynt",
        "\u0141a\u017ania",
        "\u0141uk triumfalny",
        "Mur",
        "Muzeum",
        "Obelisk",
        "Pa\u0142ac",
        "Pole bitwy",
        "Prze\u0142\u0119cz",
        "Sad",
        "Sprofanowane sanktuarium",
        "Twierdza",
        "Wie\u017ca",
        "Wilcze le\u017ce"
    ],
    "Projekt": [
        "Cathedral",
        "City Gate",
        "Pageant",
        "Sewers",
        "Star Chart",
        "Exploration",
        "Fair",
        "Silos",
        "Sinister Plot",
        "Academy",
        "Capitalism",
        "Fleet",
        "Guildhall",
        "Piazza",
        "Road Network",
        "Barracks",
        "Crop Rotation",
        "Innovation",
        "Canal",
        "Citadel"
    ],
    "Droga": [
        "Way of the Butterfly",
        "Way of the Camel",
        "Way of the Chameleon",
        "Way of the Frog",
        "Way of the Goat",
        "Way of the Horse",
        "Way of the Mole",
        "Way of the Monkey",
        "Way of the Mouse",
        "Way of the Mule",
        "Way of the Otter",
        "Way of the Owl",
        "Way of the Ox",
        "Way of the Pig",
        "Way of the Rat",
        "Way of the Seal",
        "Way of the Sheep",
        "Way of the Squirrel",
        "Way of the Turtle",
        "Way of the Worm"
    ],
    "Cecha": [
        "Bogaty",
        "Cierpliwy",
        "Inspiruj\u0105cy",
        "Nierozwa\u017cny",
        "Niestrudzony",
        "Nie\u015bmia\u0142y",
        "Odziedziczony",
        "Pobliski",
        "Pobo\u017cny",
        "Po\u015bpieszny",
        "Przekl\u0119ty",
        "Przeznaczony",
        "Przyjazny",
        "Przymilny",
        "Tani"
    ]
}
477
